# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Accidental Shakespeare
email: accshakes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Accidental Shakespeare shares stories that subvert expectations, and
  explores our common humanity in a complex world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://accidentalshakespeare.org" # the base hostname & protocol for your site, e.g. http://example.com
permalink: :path/

version:
  bulma: 0.7.1 # This depend on "cdnjs.com"
  font-awesome: 5.0.12 # This depend on "use.fontawesome.com", also name version it without "v" prefix.

sass:
  style: compressed

# For Facebook Open Graph
og_image: assets/images/accidental-shakespeare-logo.png # Default image for Open Graph tag
og_image_type: image/png
og_image_width: 245
og_image_height: 302
fb_profile_id: AccShakes
fb_admins: 196678607064611

# For Twitter Cards
twitter_username: AccShakes
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - spec/
  - vendor

collections:
  company:
    output: true
    permalink: /company/:title/
  productions:
    output: true
    permalink: /productions/:path/
  opportunities:
    output: true
    permalink: /join_us/:path/
  upcoming:
    output: true
    permalink: /upcoming/:path/
  reviews:
  sponsors:

